import { Resource } from "sst";
import { drizzle } from "drizzle-orm/aws-data-api/pg";
import { RDSDataClient } from "@aws-sdk/client-rds-data";
import * as schema from './schema';

export const db = drizzle(new RDSDataClient({region: "us-east-1"}), {
    // @ts-expect-error - This is a global variable generated by SST.
    database: Resource.GreekBookDB.database,
    // @ts-expect-error - This is a global variable generated by SST.
    secretArn: Resource.GreekBookDB.secretArn,
    // @ts-expect-error - This is a global variable generated by SST.
    resourceArn: Resource.GreekBookDB.clusterArn,
    schema
});