/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "VibePass": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "VibePassDB": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "secretArn": string
      "type": "sst.aws.Postgres"
      "username": string
    }
    "VibePassEventImages": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "VibePassVPC": {
      "type": "sst.aws.Vpc"
    }
  }
}
