/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "GreekBookDB": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "secretArn": string
      "type": "sst.aws.Postgres"
      "username": string
    }
    "GreekBookOrgEventImages": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "GreekBookVPC": {
      "type": "sst.aws.Vpc"
    }
  }
}
